### ISSUE TITLE
when i used wave file source or TS-MPEG file source we have 

### ISSUE THREAD

**Issue by stackprogramer** [csete/gnuradio-dvb#1]
hi, your project is work with gsteamer, but when i use wave file source or TS-MPEG it is has lost packet:
data and quality is lost.......
can you guide for sending file source in gnuradio with DVB?
https://drive.google.com/open?id=0Bxkt-d32S34gazJocWN5U3lnWlIyd3V0QnI5SkZwWGlqWW9z
thanks for attention best regards stackprogramer

**Comment by csete** [comment]
This repository is provided as reference, but there is really no reason for using it in new projects today. Please use the gr-dtv package already included in GNU Radio. In any case, I can not provide technical support for everything that I publish, it's just not realistic, sorry.
